version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17.1
    working_directory: ~/word-game-app

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  test-e2e:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Playwright E2E Tests
          command: npm run test:e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-e2e:
          requires:
            - build