version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17.1
    working_directory: ~/word-game-app

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
